### ISSUE TITLE
Add Ethiopian calendar and time

### ISSUE THREAD

**Issue by MenoData** [MenoData/Time4J#389]
See also:

http://ayannanahmias.com/2011/06/15/ethiopian-calendar/
https://ethiopiancalendar.wordpress.com/history/
http://abyssiniagateway.net/fidel/l10n/
https://en.wikipedia.org/wiki/Ethiopian_calendar

Time4J should be able to handle not only the calendar itself but also the Ethiopian time which starts counting on 06:00 in the morning (also start of the day). The cited link on ayannanahmias.com should be the base of the implementation. So overall it is rather a complex calendar with features far beyond what is usual in other calendar libraries - see also #362.

**Comment by MenoData** [comment]
About Ethipian time here two links:

http://www.pri.org/stories/2015-01-30/if-you-have-meeting-ethiopia-you-better-double-check-time
http://web.linkethiopia.org/guide-to-ethiopia/travellers-guide/travel-tips/time/

**Comment by MenoData** [comment]
About day divisions, we will go with CLDR data which are different from those presented at  ayannanahmias.com (this is okay due to the fact that there are differences dependent on the sub-region of Ethiopia).

**Comment by MenoData** [comment]
Day divisions are postponed to next release. For now, the calendar is finished.

**Comment by srl295** [comment]
@MenoData FYI, bug for working on this in CLDR: https://unicode.org/cldr/trac/ticket/9716
