### ISSUE TITLE
12-hour-clock requires am/pm-marker or dayperiod: EEEE, d MMMM y 'à' HH.mm:ss 'h' zzzz

### ISSUE THREAD

**Issue by jsarson** [MenoData/Time4J#583]
Hi, thanks for a fantastic library! 

I'm using Android version with current configuration:
compile 'net.time4j:time4j-android:3.24-2016i'
compile 'net.time4j:time4j-range:3.24'

On most devices, it works great, but on some is crashing. Please check the exception.

`Fatal Exception: java.lang.IllegalArgumentException: 12-hour-clock requires am/pm-marker or dayperiod: EEEE, d MMMM y 'à' HH.mm:ss 'h' zzzz
       at net.time4j.format.expert.ChronoFormatter.getLocale(Unknown Source)`

Do you have any idea what is wrong? Thanks!

**Comment by MenoData** [comment]
Obviously I have missed something when solving issue #565

**Comment by MenoData** [comment]
A pattern sanity check had been built into v3.24 in order to prevent users from doing some nonsense. Unfortunately I have overlooked that letters like 'h' can also exist in literals which should be ignored...

**Comment by jsarson** [comment]
Thanks!
