### ISSUE TITLE
Error receiving broadcast Intent

### ISSUE THREAD

**Issue by jsarson** [MenoData/Time4J#585]
Hi, please can you check this issue?

`Fatal Exception: java.lang.RuntimeException
Error receiving broadcast Intent { act=android.intent.action.TIMEZONE_CHANGED flg=0x10 } in net.time4j.android.c@411a6be0
 Raw Text
android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:765)
dalvik.system.NativeStart.main (NativeStart.java)
Caused by java.lang.NullPointerException
java.util.concurrent.ConcurrentHashMap.get (ConcurrentHashMap.java:767)
net.time4j.tz.Timezone.getTZ (Unknown Source)
net.time4j.tz.Timezone.of (Unknown Source)
net.time4j.android.ApplicationStarter$TimezoneChangedReceiver.onReceive (Unknown Source)`

Version: v3.24-2016i (Time4A)

Just a few users are affected. Thanks!

**Comment by MenoData** [comment]
This looks as if the expression `String ref = intent.getStringExtra("time-zone");` inside the class `ApplicationStarter$TimezoneChangedReceiver` yields `null`. Seems to be a little bit strange if the tz-receiver is triggered with such an event/intent. Nevertheless, I will prepare a fix to ignore the funny intent if the tz-zone-id given by intent is `null`.

**Comment by MenoData** [comment]
Another maybe better fix would be just to trigger an update of `Timezone.ofSystem()` instead of relying on the zone id obtained by broadcast intent.

**Comment by MenoData** [comment]
The observed NPE can no longer happen after refactoring, and the tz-id reported by Android in broadcast receiver is now only used for logging purposes in a safe way.
