### ISSUE TITLE
Investigate and optimize proguard configuration

### ISSUE THREAD

**Issue by MenoData** [MenoData/Time4J#710]
Some people have reported app crashes when deserializing compiled tz data, although I have not yet been able to reproduce it. Anyway, a closer look at [current proguard rules](https://github.com/MenoData/Time4A/blob/master/time4j-android/consumer-proguard-rules.pro) makes sense for sake of robustness. 

About serialization and proguard see also: https://www.guardsquare.com/en/proguard/manual/examples#serializable

Another example is interesting for comparison and maybe reproducibility: https://github.com/reisub/ZonedDateTimeProguardBug

**Comment by MenoData** [comment]
Meanwhile I have been able to reproduce the abort in case of applying Proguard by setting up an extra app-integration-project-test.

@forrestguice Can you confirm that the new consumer proguard rules fix your problem? The test dependency (only available on bintray but not on maven) is: `net.time4j:time4j-android:3.36.1-TEST`

**Comment by forrestguice** [comment]
Confirmed. No errors or anything unusual to report. Its testing fine.

**Comment by MenoData** [comment]
Thank you very much for your observation and helping with test. I will soon try to delete the test release. And the next release v3.37-2017c is not far away...
