### ISSUE TITLE
Duplicate Android resource @string/app_name and application@label

### ISSUE THREAD

**Issue by msrd0** [MenoData/Time4J#726]
I just tried to add the latest version of Time4A to my android app but I got the following error message:

```
Manifest merger failed : Attribute application@label value=(@string/app.name) from AndroidManifest.xml:22:18-50
	is also present at [net.time4j:time4j-android:3.37-2017c] AndroidManifest.xml:13:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:21:5-32:19 to override.
```

So, I added `tools:replace="android:label"` and got another error:

```
Duplicate symbol in table with resource type 'string' and symbol name 'app_name'
```

Since I don't see a reason why a library has to define `@string/app_name` or `application@label`, could you please either give me a reason why those definitions exist or remove them?

**Comment by MenoData** [comment]
Thanks for your feedback. I appreciate it. Well, the original version of android-manifest was just overtaken from my first experiments with Android Studio. And I agree with you that an aar-library-module does not need to define any app properties. 

The idea for the new committed version comes from this SO-thread:

https://stackoverflow.com/questions/28157981/does-an-android-library-need-a-manifest-app-name-icon

That is:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest 
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="net.time4j.android">

    <application />
</manifest>

```
Please feel free to share with others your opinion about the new version or suggest any improvements. I will test it this weekend.

**Comment by MenoData** [comment]
See also the [original documentation from Android](https://developer.android.com/guide/topics/manifest/manifest-intro.html). It says:

> Elements
>     Only the `<manifest>` and `<application>` elements are required. 
> 
> Attributes
>     In a formal sense, all attributes are optional. However, there are some attributes that must be specified so that an element can accomplish its purpose. Use the documentation as a guide. For truly optional attributes, it mentions a default value or states what happens in the absence of a specification. 
>

**Comment by msrd0** [comment]
I fully agree with the SO-thread you linked above. Thanks for removing the app-properties from the android manifest.

Still, I have a problem because of the duplicate string resource `app_name` in both my android app and your library. Could you remove it from [`strings.xml`](https://github.com/MenoData/Time4A/blob/8b086e9/app/src/main/res/values/strings.xml#L2) (I assume it's not needed)? Probably some of the other string resources are also unused in your library

**Comment by MenoData** [comment]
I have now cleaned up all string resources in Time4A (including those in the demo-app) and tested it in the emulator of Android Studio. Works for me.

**Comment by msrd0** [comment]
OK cool thanks

**Comment by MenoData** [comment]
You can now try out the new release

dependencies {
    compile group: 'net.time4j', name: 'time4j-android', version: '3.38-2017c'
}

I think your problem should be solved because there cannot be any duplicate string resources in the new release.
