### ISSUE TITLE
How to represent an empty DateInterval

### ISSUE THREAD

**Issue by charlesxucheng** [MenoData/Time4J#771]
Hi there,

Is there recommended way to get an Empty DateInterval instance?

What I did is a bit hackish and is only used in test code only, but I now have a case to do so in production code...

def emptyInterval: DateInterval = DateInterval.between(DateHelper.MAGIC_DATE, DateHelper.MAGIC_DATE).withOpenStart()

**Comment by MenoData** [comment]
Nice to get your feedback. I appreciate it. Until now, there is no special public method for creating empty date intervals. However, as you noted, several workarounds are possible. I myself have applied following method in a [test class](https://github.com/MenoData/Time4J/blob/c24c6d147a954280e58370f0f50d8e9db9cfc9c9/range/src/test/java/net/time4j/range/BasicDateRangeTest.java#L161):

```
     @Test 
     public void isEmptyAtomicOpen() { 
         PlainDate date = PlainDate.of(2014, 5, 14); 
         assertThat( 
             DateInterval.atomic(date).withOpenEnd().isEmpty(), 
             is(true)); 
     } 
```

Your solution is not wrong but I prefer a closed start of interval. Furthermore, Even an empty interval has still an anchor on the date line, hence the requested date parameter. 

If you wish then I can incorporate a small change to API of `DateInterval` in next release v4.37 for convenience based on given example in my test class.

**Comment by charlesxucheng** [comment]
Thanks! That will be helpful!
