### ISSUE TITLE
Weeks between two Julian dates returns an incorrect value

### ISSUE THREAD

**Issue by iamcalendar** [MenoData/Time4J#775]
**Example:**
```
JulianCalendar date1 = JulianCalendar.of(HistoricEra.AD, 1, 1, 1)
JulianCalendar date2 = JulianCalendar.of(HistoricEra.AD, 10_000_000, 1, 1)
long weeks = JulianCalendar.Unit.WEEKS.between(date1, date2) 
```
Version: 3.41
Return value: -91781094
Expected value: 521785662

Reason:
The expected value cannot be represented by `int`

**Comment by MenoData** [comment]
Thank for your feedback. Am going to fix it soon.

**Comment by MenoData** [comment]
The fix uses a safe cast to int-primitive now (and a few internal improvements for safety). The return type of between-method is still an int for backwards compatibility reasons. If this is not sufficient then you can apply the safe alternative `start.until(end, unit)` which only operates on longs.
