### ISSUE TITLE
Incorrect translation of "M" pattern in JulianCalendar formatter

### ISSUE THREAD

**Issue by iamcalendar** [MenoData/Time4J#776]
**Example:**
```
JulianCalendar date = JulianCalendar.of(HistoricEra.AD, 2018, 4, 29);
ChronoFormatter<JulianCalendar> formatter = ChronoFormatter.ofPattern("M", PatternType.CLDR, Locale.ENGLISH, JulianCalendar.axis());
String dateString = formatter.format(date);
```
Version: 3.41
Output: "April"
Expected output: "4"

**Comment by MenoData** [comment]
The Julian calendar has been developed as a side product of the historic calendar, so using historic month elements which were only designed for textual output. I think, this is unfortunate and should be changed in context of CLDR-patterns such that numeric formatting is also supported.

**Comment by MenoData** [comment]
A temporary workaround is:

		ChronoFormatter<JulianCalendar> formatter =
			ChronoFormatter
				.setUp(JulianCalendar.axis(), Locale.ENGLISH)
				.addInteger(JulianCalendar.MONTH_OF_YEAR, 1, 2)
				.build();
