### ISSUE TITLE
Problem with java 10 project jigsaw

### ISSUE THREAD

**Issue by LightGuardian7** [MenoData/Time4J#777]
I was using calendar, core, ui,range and i18n jar files with java 8 and every thing worked fine.
After update to java 9 with a modular design time4j liberaries seem to have a conflict.
My program is running correctly without time4j but when I include those 5 jar files I get this error.

module time4j.i18n reads package net.time4j.format.internal from both time4j.i18n and time4j.core
module time4j.core reads package net.time4j.format.internal from both time4j.i18n and time4j.core
module time4j.range reads package net.time4j.format.internal from both time4j.i18n and time4j.core
module time4j.ui reads package net.time4j.format.internal from both time4j.i18n and time4j.core
module time4j.calendar reads package net.time4j.format.internal from both time4j.i18n and time4j.core
module mra.tools.forms reads package net.time4j.format.internal from both time4j.i18n and time4j.core

Got same results on java 10

By removing core liberary I get this error on using PersianCalendar class

Type parameter net.time4j.calendar.PersianCalendar is not within its bounds; should extend net.time4j.engine.CalendarDate

My test enviroment is : JavaFx - Sun Java 10.0.1 - Jetbrains Intellij Idea 2018-1 - Windows 10

Please help me with a solution. Maybe I'm not using it right.
Thanks

**Comment by MenoData** [comment]
Sorry to hear your problems. The truth is: I have not yet tested Time4J with Java 9 or later (on the module path). Time4J is actually only designed for the class-path, not for the module path. Anyway, I will take it into account when designing the next major version v5.0 with a changed modular design. But it will take some time.

Some of my plans for v5.0 are:

a) the service loader mechanism (heavily deployed by Time4J until now) will just be a fallback,

b) user-defined services/modules will need to be programmatically registered,

c) several Time4J-modules like core, i18n, calendar etc. will be unified to one module (which will probably solve your issue)

**Comment by LightGuardian7** [comment]
Thanks

**Comment by MenoData** [comment]
I have now done a first test in jigsaw environment using Java 10 with the new module structure (most classes in new `net.time4j.base`-module which will work as "automatic module"). Unfortunately the main obstacle is now the internal usage of `ResourceBundle` which does not work any longer on the module path. I will tackle this issue (#786) soon.

Another smaller obstacle is to slightly modify the service loader mechanism (will be similar to what I already use in Time4A on Android), not such a big deal.

**Comment by MenoData** [comment]
Now I have released the major version v5.0 which fixes your problem. Use the new dependency "time4j-base". If you also use the tzdata then use the latest one (v5.0-2018f) and don't forget to call first `TZDATA.init()` before any other Time4J-code.

I have explicitly verified the new setup in a Java-10-environment on the module path.
