### ISSUE TITLE
Exit and arrival of the moon to the zodiac sign

### ISSUE THREAD

**Issue by discovererer** [MenoData/Time4J#778]
```
Moment moment = PlainTimestamp.of(2018, 4, 1, 0, 0).atUTC();
Zodiac.Event ze = MoonPosition.inSignOf(Zodiac.SCORPIUS);
Moment entry = ze.atMomentOfEntry(moment);   //2018-04-01T22:57:14Z
Moment Exit = ze.atMomentOfExit(moment);     //2018-04-01T22:57:14Z
```
If I'm not mistaken, 
the duration between these two moments is about two or three days!

**Comment by MenoData** [comment]
Thanks for feedback! For me, this result is expected and not surprising. Keep in mind that the revolution of the moon around the earth takes about 29.5 days roughly corresponding to a full angle of 360° on the zodiac circle. Approximating one single zodiac constellation by an angle of 360/12, you get 29.5 / 12 days ~ 2-3 days. The moon is indeed moving quickly through the sky which makes somehow precise calculations a challenge (also for moonrise/moonset).

**Comment by MenoData** [comment]
Sorry, I think I have misunderstood you and have to check it myself. The SAME time should not happen.
