### ISSUE TITLE
NullPointerException when I trying to convert Windows zones to IANA 

### ISSUE THREAD

**Issue by RomaSha2009** [MenoData/Time4J#785]
Hi!
Need assistance.

I need to get time zones from my DB which are stored as Windows zones. I need to convert them into IANA. I have found your library.
Also I have found example how to do that:
}
  WindowsZone wzn = WindowsZone.of("Eastern Standard Time");
  TZID winzone = wzn.resolveSmart(Locale.US);
  System.out.println(winzone.canonical());
// WINDOWS~America/New_York
}

In my case I am trying to convert Windows Zones "FLE Standard Time" and "Arabic Standard Time" in such way

 }
 WindowsZone wzn = WindowsZone.of("FLE Standard Time");
  TZID winzone = wzn.resolveSmart(Locale.ENGLISH);
  System.out.println(winzone.canonical());
}

And Arabic:

}
 WindowsZone wzn = WindowsZone.of("Arabic Standard Time");
  TZID winzone = wzn.resolveSmart(Locale.ENGLISH);
  System.out.println(winzone.canonical());
}

In both cases I am receiving java.lang.NullPointerException
What I doing wrong? I don't get it. Test example is working properly. But at the same time my methods are not.
Please help me. I guessing my mistake in Locale. But I'm not sure

**Comment by MenoData** [comment]
The javadoc says:

`public TZID resolveSmart(Locale country)`

> Resolves this name reference to at most one zone id for given country. 
> 
> Normally windows zones cannot be resolved to one single zone id, but there is usually one preferred zone id based on the fact that the daylight saving rules for this name and given country are often the same for all belonging zone ids in the recent past. This method tries its best to yield a result but applications have to check if the result is null. 
> 
> Parameters: country - country reference
> Returns: preferred zone id belonging to this windows zone or null if given country is not related to this 

nameSince:2.2

**Comment by MenoData** [comment]
About "Arabic Standard Time", consider following example:

```
	WindowsZone wzn = WindowsZone.of("Arabic Standard Time");
	TZID winzone = wzn.resolveSmart(new Locale("en", "IQ"));
	System.out.println(winzone.canonical()); // WINDOWS~Asia/Baghdad
```

**Comment by RomaSha2009** [comment]
Thank you man! Really grateful to you! I will proceed my work thanks to you.

**Comment by MenoData** [comment]
Now I have changed the signature and behaviour of the method `resolveSmart(...)`. 

a) It will return a `java.util.Optional<TZID>` (avoiding simply returning `null`). 

b) And you will no longer need to use the 001-hack. Example:

```
WindowsZone wzn = WindowsZone.of("Arabic Standard Time");
TZID winzone = wzn.resolveSmart(new Locale("en", "US")).get(); // don't forget to check if present
System.out.println(winzone.canonical()); //WINDOWS~Asia/Baghdad"

```

**Comment by RomaSha2009** [comment]
Thanks for update :)
