### ISSUE TITLE
Throwing IllegalArgumentException in background thread of ApplicationStarter

### ISSUE THREAD

**Issue by iamcalendar** [MenoData/Time4J#790]
We have received an exception as below:
```
java.lang.IllegalArgumentException:
1. at net.time4j.tz.Timezone.a (Timezone.java:253)
2. at net.time4j.tz.Timezone.a (Timezone.java:15)
3. at net.time4j.tz.Timezone.a (Timezone.java:1)
4. at net.time4j.format.expert.ChronoFormatter.access$1000 (ChronoFormatter.java)
   or                     .access$1100 (ChronoFormatter.java)
   or                     .access$700 (ChronoFormatter.java)
   or                     .addPattern (ChronoFormatter.java)
   or                     .checkConsistency (ChronoFormatter.java)
   or                     .display (ChronoFormatter.java)
   or                     .format (ChronoFormatter.java)
   or                     .format0 (ChronoFormatter.java)
   or                     .formatToBuffer (ChronoFormatter.java)
   or                     .freeze (ChronoFormatter.java)
   or                     .getChronology (ChronoFormatter.java)
   or                     .getReason (ChronoFormatter.java)
   or                     .isEqual (ChronoFormatter.java)
   or                     .ofDatePattern (ChronoFormatter.java)
   or                     .ofMomentStyle (ChronoFormatter.java)
   or                     .ofPattern (ChronoFormatter.java)
   or                     .parse (ChronoFormatter.java)
   or                     .parseElements (ChronoFormatter.java)
   or                     .print (ChronoFormatter.java)
   or                     .rfc1123DateTime (ChronoFormatter.java)
   or                     .setUp (ChronoFormatter.java)
   or                     .sub (ChronoFormatter.java)
   or                     .updateSelf (ChronoFormatter.java)
   or                     .with (ChronoFormatter.java)
   or                     .withTimezone (ChronoFormatter.java)
5. at net.time4j.format.expert.ChronoFormatter.a (ChronoFormatter.java:22)
6. at net.time4j.android.ApplicationStarter$1.run (ApplicationStarter.java:38)
7. at java.lang.Thread.run (Thread.java:784)
```
It sounds like the exception is thrown in background thread of net.time4j.android.ApplicationStarter class (line 153) when tries to format the current moment:
```
Log.i(
    TIME4A,
    ChronoFormatter.ofMomentStyle(
        style,
        style,
        sysloc,
        tzid
    ).format(SystemClock.currentMoment())
);
```
We are wondering if you have any idea why this happens? Please let us know if you require any further information. Thanks again for your kind help!

**Comment by MenoData** [comment]
Hm, I really miss the message of the exception shown above, and I don't know or remember any place in Time4A-code where an `IllegalArgumentException` is produced without any detail message (that is only with the stack trace and nothing else). Such an exception is expected if anything is wrong with the time zone and would show (in its detail message) the problem time zone identifier.

Can you please check your exception handling or look for any other Time4A-related logs which might show more details?

**Comment by iamcalendar** [comment]
Thanks for responding to our question. This is all we got from the play store crash report. We agree with you that the exception message is missing. If we get more info we will let you know. Thanks for your time.

**Comment by MenoData** [comment]
Maybe this [link](https://github.com/brave/browser-android-tabs/wiki/How-to-see-exception-message-while-crash-analyst-in-GP-Dev-console) contains some helpful info how to look for the detail message.

Another link which might be useful, too:

https://stackoverflow.com/questions/48692071/google-play-store-crash-reports-incomplete-missing-most-of-the-data

**Comment by iamcalendar** [comment]
Thanks again for your help. Unfortunately, the Google Play Developer Console does'nt present the detail message. As explained in this [link](https://stackoverflow.com/questions/47326896/vital-information-missing-from-google-play-developer-console-crash-reports), it is a known issue but not fixed yet. [This](https://www.reddit.com/r/androiddev/comments/6ihcr7/exception_messages_missing_in_new_play_console/) is another complaint.

**Comment by MenoData** [comment]
The first link I had given to you states that it might be possible to see the details after having downloaded csv-files as reports from Google. How to download (have not tested it myself though) is explained in the section "Download reports from Google Cloud Storage":

https://support.google.com/googleplay/android-developer/answer/6083203?hl=en

**Comment by iamcalendar** [comment]
We examined your links but we did not get more information.

The section "Download reports from Google Cloud Storage" has a link to the following page:
https://support.google.com/googleplay/android-developer/answer/6135870

In this page, the section "Crashes & ANRs" states that: 
> As of May 2018, you can no longer download detailed reports for crashes and ANRs.

**Comment by MenoData** [comment]
Sorry to hear this. So what can we do now? Without the detail message, there is no chance to fix or to reproduce your issue. I don't understand Google here. About practical consequences in the app:

- Waiting for Googles solution for the serious defect of exception reports
- It is only the prefetch thread which fails so other parts of the app might still work???
- Something with `Timezone.ofSystem().getID()` might be wrong on special devices (just a feeling now)
- You might try out the alternative `Timezone.ofPlatform()` using the device data in the app
- ...

**Comment by iamcalendar** [comment]
At the moment, we don't have a crash/exception tracker system as we don't ask users for Internet permission (in future if we add a feature that requires Internet permission then we will definitely consider adding crash/exception analytics). For now there is nothing much we can do on our side unless wait for Google solution for exception messages. We plan to not let throw an exception for this particular case (hope this helps).

Thanks for releasing new version with `HirjiAdjustment`-issue fix. As always, we really appreciate your time and consideration.

**Comment by MenoData** [comment]
I have also committed a small change in both Time4J and Time4A in order to improve the handling of customized zone identifiers. If such a non-standard id is found then the code will first check if it is the id of the current system time zone before throwing an exception. Maybe your issue will completely go away with this change.

**Comment by iamcalendar** [comment]
Not sure if this helps but we received again the same crash twice. We have got the crash only on Android 8.0 devices. We guess there is a problem with this version of Android.

**Comment by MenoData** [comment]
Now I have released Time4A-v3.44-2018e which might let your issue go away.

**Comment by MenoData** [comment]
The referenced issue given by @fnlctrl also indicates that this issue is solved.

**Comment by MenoData** [comment]
Please use v3.44.1-2018e (or later) with an important fix for a crash in determining the system timezone.
