### ISSUE TITLE
Throwing IllegalArgumentException while formatting minimum date of Minguo calendar

### ISSUE THREAD

**Issue by iamcalendar** [MenoData/Time4J#792]
After running the following code
```
CalendarSystem<MinguoCalendar> calsys = MinguoCalendar.axis().getCalendarSystem();
MinguoCalendar minDate = calsys.transform(calsys.getMinimumSinceUTC()); // BEFORE_ROC-1000001911-01-01
ChronoFormatter<MinguoCalendar> formatter = ChronoFormatter
        .ofPattern("yyyy", PatternType.CLDR, Locale.ENGLISH, MinguoCalendar.axis());
System.out.println(formatter.format(minDate));
```
we get
```
IllegalArgumentException: Element YEAR_OF_ERA cannot be printed as the formatted value 1000001911 exceeds the maximum width of 9.
```
while expecting `1000001911` as output (because `minDate` is formattable).

We suggest to change the minimum date of Minguo calendar to `BEFORE_ROC-999999999-01-01`

In other word, we suggest to override `getMinimumSinceUTC` method of `MinguoCalendar` class as
```
@Override
public long getMinimumSinceUTC() {
    return -365242521549; // BEFORE_ROC-999999999-01-01
}
```

**Comment by MenoData** [comment]
Sounds reasonable (minimum effort for making such extreme values formattable which is more important than to support the edge case value itself).

**Comment by MenoData** [comment]
Similar problem also located in Julian calendar, Thai solar calendar. Let's favor formattability for such extrem values.

**Comment by MenoData** [comment]
I have now extended the general formattability of integer elements up to 10 digits (see issue #797). This solves your problem, too. Do you still insist on adjusting the value ranges of `MinguoCalendar` or `ThaiSolarCalendar`? Keep in mind that the actual ranges fit well with the range of `PlainDate`.

**Comment by iamcalendar** [comment]
No need to adjust the range. Thanks!

**Comment by MenoData** [comment]
Okay, then I can close this issue, too (indirectly fixed by issue #797). The next release is not far away (maybe next week).

**Comment by iamcalendar** [comment]
Unfortunately the problem exists in Time4A version 3.44.4-2018e.

**Comment by MenoData** [comment]
Will have a look soon...

**Comment by MenoData** [comment]
Sorry for this oversight. But I have now also added your example as (successful) test case.
