### ISSUE TITLE
Throwing IllegalArgumentException while formatting maximum date of Thai solar calendar

### ISSUE THREAD

**Issue by iamcalendar** [MenoData/Time4J#793]
Similar to [this issue](https://github.com/MenoData/Time4J/issues/792), we get `IllegalArgumentException` after running the following code
```
CalendarSystem<ThaiSolarCalendar> calsys = ThaiSolarCalendar.axis().getCalendarSystem();
ThaiSolarCalendar maxDate = calsys.transform(calsys.getMaximumSinceUTC()); // BUDDHIST-1000000542-12-31
ChronoFormatter<ThaiSolarCalendar> formatter = ChronoFormatter
        .ofPattern("yyyy", PatternType.CLDR, Locale.ENGLISH, ThaiSolarCalendar.axis());
System.out.println(formatter.format(maxDate));
```
We suggest to override `getMaximumSinceUTC` method of `ThaiSolarCalendar` class as
```
@Override
public long getMaximumSinceUTC() {
    return 365241581415L; // BUDDHIST-999999999-12-31
}
```

**Comment by MenoData** [comment]
Thank for your hint. I think similar thoughts are also valid for the Julian calendar. I am closing this as duplicate and let apply the other related issue tracking this, too.
