### ISSUE TITLE
Wrong lengthOfYear for first year of ThaiSolarCalendar

### ISSUE THREAD

**Issue by iamcalendar** [MenoData/Time4J#794]
Example:
```
CalendarSystem<ThaiSolarCalendar> calsys = ThaiSolarCalendar.axis().getCalendarSystem();
ThaiSolarCalendar minDate = calsys.transform(calsys.getMinimumSinceUTC()); // BUDDHIST-1-04-01
System.out.println(minDate.lengthOfYear());
```
Version: 4.38
Output: 365
Expected output: 275

**Comment by MenoData** [comment]
Why should the first buddhist year 1 only have 275 days? It started on April - 1st and ended on March 31th (no leap day => 365 days).

**Comment by iamcalendar** [comment]
Thanks for your explanation. That was my misunderstanding.
