### ISSUE TITLE
Support Badi calendar

### ISSUE THREAD

**Issue by MenoData** [MenoData/Time4J#798]
See also Wikipedia and the proposal for dot.net-world:

- https://wikipedia.org/wiki/Badi_calendar
- https://github.com/dotnet/corefx/issues/30207
- http://www.religiouslife.emory.edu/documents/Baha_i%20Holy%20Days%2050%20year%20calendar.pdf

Reingold/Dershowitz described the calendar, too (as Bahai calendar).

**Comment by glittle** [comment]
@MenoData If you have any questions about implementing the Badíʿ calendar, feel free to run them by me! I'll help however I can.

**Comment by MenoData** [comment]
Thank you very much for your offer. I would especially need your help on the area of internationalization while the algorithm itself is more or less well documented. For example, one question immediately arises: How to print/format the Ayam-i-ha days? Will this always happen in a textual way? If yes, how? Or do people ever use numbers (my doubt: a symbolic month number like zero is rather an artificial invention which I would like to avoid). Are abbreviations also used? About language support, I would welcome at least English, Farsi and Arab (maybe also Pashto or more ;-)).

**Comment by glittle** [comment]
Sure, I'll take a look.  

My most up-to-date source of translations for the Badíʿcalendar can be found here: https://github.com/glittle/badi-chrome-ext/tree/master/_locales  This includes lots of other text not needed for the calendar, but for most of the languages listed, the months are translated.

**Comment by glittle** [comment]
There is some confusion about the name of the calendar. The calendar should ideally be referred to as the " Badíʿ " calendar, or in code, can use "Badi" without the accent and arabic `ayn symbol.  The Badíʿ calendar is closely associated with the Baha'i Faith but can be used without any reference to the religion.

**Comment by MenoData** [comment]
Agreed. The new calendar should be named "BadiCalendar" (in Java code).

About my intentions, the scope of Time4J-implementation is always more than just an algorithm to convert programmatically to and from gregorian calendar. Proper internationalization is also important and a key feature of Time4J. This includes as many customized formats in different languages as users might think of. The format engine of Time4J is flexible enough to do that. My concrete thoughts:

**Algorithm**: I am aware of the change of year start beginning on vernal equinox which took effect in year 2015 and later. You speak about a table of data as used in NodaTime. I can see what is published by the Bahai world center (link given above in my first post). That is a prediction of dates for the year range 2015-2065 (50 years). Well, since this is official, I would adopt such a table but I am also able to extend the supported range by means of astronomical calculations of vernal equinox until (gregorian) year 3000, see the [API](http://time4j.net/javadoc-en/net/time4j/calendar/astro/AstronomicalSeason.html). Does NodaTime stop in year 2065? The rest of the algorithm is then straightforward and similar to what I have used in my implementation of the Persian calendar. And for the years before 2015, I would just follow the western style to let start a year on 21th of March (since Bahai epoch in 1844).

**The topic of Ayyam-i-Ha.** This is an exciting question. Obviously it has NO number. At least I could not see any number associated with Ayyam-i-Ha on any Wikipedia site, And also not on the screenshots of your software. There is even a pie chart only containing the regular months - without Ayyam-i-Ha. The problem to introduce a symbolic number like zero is also that such a technical feature can cause misleading comparisons because "0" is before any month number but Ayyam-i-Ha is really between 18th and 19th month. So my strong tendency is to handle Ayyam-i-Ha not as month but as a separate type (okay, I could still introduce a common interface and comparator for comparison purpose. In terms of design, this means:

- We have separate elements for months and Ayyam-i-Ha as entry points for programmatical access.
- Months would have a number (1-19), but Ayyam-i-Ha not.
- The CLDR-pattern type is not useable so we introduce another dynamic pattern type with self-defined symbols to describe formats. This is a very similar decision like in my implementation of the [French Revolutionary calendar](http://time4j.net/javadoc-en/net/time4j/calendar/frenchrev/FrenchRepublicanCalendar.html). Avoiding the CLDR-standard of the unicode consortium is IMHO okay because it does not define any resources nor any other help for the Badi calendar and is mainly designed for purely era-year-month-day-calendars (which Badi calendar is not due to the intercalary days).
- Parsing of texts which might either be month-based or include intercalary days is not difficult. That feature can easily supported by or-patterns like "YYYY-MM-dd|YYYY-A-dd" (where a pattern symbol A would represent Ayyam-i-Ha, M representing a month 1-19 and the char "|" defining an or-instruction for the parser.
- As summary, the question how to represent the Ayyam-i-Ha days (with number or only as text) is indeed the crucial item with deep impact on the whole calendar design. My suggestion: Separation of things which don't belong together and need to be handled differently.

So far my thoughts and thank you very much for your valuable contributions.

**Comment by MenoData** [comment]
About the transcription of month names like "Sharaf" or an partially underlined version (concerning the first two letters), I could support both variants. The underlined version would contain embedded html-characters (using a css-style-attribute) and is an additional entry in the text resources. I could let the user choose it by passing an extra format control attribute to the formatter/parser (where the parser should be tolerant though).

Should the underlined version be the standard?

As you can see, internationalization is often more effort than the conversion algorithm itself (underestimated by many people which try to implement calendars).

**Comment by glittle** [comment]
You may also want to read through the proposal and discussion at https://github.com/dotnet/corefx/issues/30207.  The initial entry in that issue was updated to reflect the results of the discussion below it.

**Comment by MenoData** [comment]
Ok, this calendar is almost finished leaving aside the topic of bahai-specific holidays. It is defined from gregorian year 1844 until 2927. @glittle Please can you tell me what kind of week definition is usual? Until now, I have assumed: Saturday as first day of week, first week of year only needs one day to be defined, and Saturday/Sunday is the weekend. Do the Bahai community use another weekend definition? Maybe like in Iran (then just Friday)?

**Comment by glittle** [comment]
Sounding good. For weeks, Saturday is considered to be the first day of the week. I don't know of any concept of a "weekend".  In practice, the week is not a significant concern and whatever is common in the culture is used.

**Comment by glittle** [comment]
Just looked through the coding.  You've done a great job!  I like the approach to dealing with "the days in excess of the months"!

**Comment by MenoData** [comment]
@glittle Okay, I will keep the default week model private because there is no standard. Bahai holidays (mainly the twin holy days using moon astronomy) will be implemented later for the sake of releasing the actual state as soon as possible (main reason is: a new Japanese nengo/era will be introduced on coming first of May). I will just do some extra tests (for example unit arithmetic), and then I can release the Badi calendar and the new Nengo for Japanese calendar.

**Comment by glittle** [comment]
I don't consider the holidays to be a part of the Badí' calendar. Instead, they are the celebrations of a particular religion, the Bahá'í Faith.

**Comment by MenoData** [comment]
@glittle I am aware of the fact that the Badi calendar is intended by its promoters to be a universal calendar also for non-religious purposes. Anyway, several of the calendars in Time4J offer some extra services for calculating holidays (which is often the main purpose), for example the Chinese calendar or the Hebrew calendar because some calculations are tricky and require astronomy. However, this does not form a replacement for a truely holiday module or library. But maybe the Bahai holidays can be a start for an extra holiday module...
