### ISSUE TITLE
Unexpected date while getting a specified day of year in HebrewCalendar

### ISSUE THREAD

**Issue by iamcalendar** [MenoData/Time4J#800]
Example:
```
HebrewCalendar date = HebrewCalendar.ofCivil(9999, 12, 29) // AM-9999-ELUL-29
        .with(HebrewCalendar.DAY_OF_YEAR, 1);
System.out.println(date);
```
Version: 4.38
Output: AM-9998-AV-30
Expected output: AM-9999-TISHRI-01

**Comment by MenoData** [comment]
Thank you very much for the message. At least the method to determine day-of-year is wrong. I will fix it as soon as possible (although I am very busy now with other things).

**Comment by MenoData** [comment]
I have finished my analysis and found that following small correction in [`HebrewCalendar`-class](https://github.com/MenoData/Time4J/blob/master/base/src/main/java/net/time4j/calendar/HebrewCalendar.java#L1558) should be sufficient to fix this issue and also all negative side effects:

		boolean leap = HebrewCalendar.isLeapYear(context.year);
		for (int m = 1; m < context.month.getValue(); m++) {
			if (leap || (m != 6)) {
				doy += CALSYS.getLengthOfMonth(HebrewEra.ANNO_MUNDI, context.year, m);				}
		}
