### ISSUE TITLE
Mismatch between getMinimumSinceUTC and transform for some historic calendars

### ISSUE THREAD

**Issue by iamcalendar** [MenoData/Time4J#808]
In the following snippet is it expected to have **Failure!** shown in the output?
```
ChronoHistory[] histories = {
        ChronoHistory.PROLEPTIC_BYZANTINE,
        ChronoHistory.of(new Locale("", "ES")), // Spain
        ChronoHistory.of(new Locale("", "PT")) // Portugal
};
for (ChronoHistory history : histories) {
    CalendarSystem<HistoricCalendar> calsys = HistoricCalendar.family().getCalendarSystem(history.getVariant());
    try {
        calsys.transform(calsys.getMinimumSinceUTC());
        System.out.println("Success");
    } catch (IllegalArgumentException e) {
        System.out.println("Failure!");
    }
}
```

**Comment by iamcalendar** [comment]
Also, we get strange results when running the following code:
```
ChronoHistory history = ChronoHistory.of(new Locale("", "IT", ""));
CalendarSystem<HistoricCalendar> calsys = HistoricCalendar.family().getCalendarSystem(history.getVariant());
HistoricCalendar date = calsys.transform(calsys.getMinimumSinceUTC());
System.out.println(date.getDayOfYear()); // -2147483648
System.out.println(date.lengthOfMonth()); // -1
System.out.println(date.lengthOfYear()); // -1
```
Did we miss anything, or is it a bug?

**Comment by MenoData** [comment]
Sorry for the postpone but these days I am very busy with job and family. I will investigate the edge case of supported minimum of historical dates. **In general, it is expected that different historic variants have different minima.** For example, a proleptic Julian calendar has a minimum far before the historical introduction of Julian calendar by Caesar (in BC45?). However, a round-turn-trip should be always possible so the observed behaviour needs improvement.

**Comment by MenoData** [comment]
Okay, now the proleptic histories are much better handled: proleptic gregorian has same ranges as `PlainDate`, and the other proleptic variants are close to gregorian range (with the small limitation that the min- or max-years have to be full calendar years from January 1 to December 31 resulting in a slightly smaller range).

All other histories have the range BC 45 until AD 9999 and always model full calendar years which ensures that expressions like `date.getDayOfYear()` or `date.lengthOfMonth()` yield properly defined values. I have also taken your code examples as JUnit-tests which now run successfully.

And for all normal historic dates further away from the calendar range limits are okay and unchanged as before.

**Comment by iamcalendar** [comment]
Thank you very much for your attention and support.
