### ISSUE TITLE
Custom duration separators

### ISSUE THREAD

**Issue by pzielinski86** [MenoData/Time4J#839]
Hello,

I am trying to have a custom separator in PrettyTime to display "and" instead of "," - "1 year and 1 day" instead of "1 year, 1 day".
According to https://stackoverflow.com/questions/24524529/time-interval-localization-in-java  ("It supports locale-dependent list patterns (usage of comma, space or words like "and""), Time4j supports it. Unfortunately it is not clear for me how to do it.

**Comment by MenoData** [comment]
I had also thought about customized list patterns aka duration separators recently. Until now, locale-dependent list patterns simply mean that the locale controls the list pattern i.e. how the separators look like. A customized separator would no longer be a localized solution but might nevertheless be an interesting feature to realize alternative list formats. For example, following two methods might be added to `net.time4j.PrettyTime`:

```
public PrettyTime withSeparatorInside(String sep);

public PrettyTime withSeparatorAtEnd(String sep);

```

What do you think? Any suggestions else?

**Comment by MenoData** [comment]
About your concrete example, I think that the actual version of Time4J (v5.1) already supports what you want:

        Duration<?> duration =
            Duration.ofCalendarUnits(1, 0, 1);
        assertThat(
            PrettyTime.of(Locale.UK).print(duration, TextWidth.WIDE),
            is("1 year and 1 day"));

**Comment by pzielinski86** [comment]
This prints "1 year, 1 day". It would be nice to have a way to format it, even if it would have to be localized by a client.

For example in .NET Humanizer library it's possible to do: "TimeSpan.FromMilliseconds(1299630020).Humanize(3, collectionSeparator: " - ")"

https://github.com/Humanizr/Humanizer

**Comment by MenoData** [comment]
For me, I cannot reproduce your statement about the result "1 year, 1 day" for UK-locale, see my JUnit-test above. Maybe you use another locale or a very old version of Time4J. Anyway, I will go to implement the suggested two new customizer methods in the next release (I think still this year).

**Comment by MenoData** [comment]
I have now introduced following two new methods in the class `net.time4j.PrettyTime` with release v5.2:

```
public PrettyTime withDefaultListSeparator(String separator)
public PrettyTime withLastListSeparator(String separator)

```
