### ISSUE TITLE
anomalistic month (apogee/perigee)

### ISSUE THREAD

**Issue by forrestguice** [MenoData/Time4J#859]
I need to determine the start and midpoint of the anomalistic month (perigee and apogee). I'd like to produce something similar to [this](https://www.timeanddate.com/astronomy/moon/distance.html). 

Its already possible to get the distance at a given moment but I don't think there are methods that return the time of perigee or apogee. I think a method that returned the moment of upcoming perigee (occurring on-or-after a given moment) would be helpful. Is this an enhancement that can be added to the `MoonPosition` class?

**Comment by MenoData** [comment]
Okay, I will have a look soon... It will probably be doable.

**Comment by forrestguice** [comment]
Thanks @MenoData. I appreciate the work put into this. 

I'll put it to use in https://github.com/forrestguice/SuntimesWidget/issues/296. I gather that its useful info for making tide predictions.

**Comment by MenoData** [comment]
@forrestguice I think, I can do a release maybe on weekend. And the first use case of this kind of calculations which came into my mind was rather the group of photographers who want to know on which date/night they can take a photo of super moon (oversized in perigee).
