### ISSUE TITLE
[Time4A] Get month distance between 2 plaindate

### ISSUE THREAD

**Issue by kingvhit** [MenoData/Time4J#877]
I have followed the step of duration to get the distance between 2 dates but the result is not my expected.
This is a code sampe I use

```
beginDate = 31/08/2019
endDate = 05/09/2019
```
I want to get the month's distance between `begin` and `end` date, the result must be `1` 
but it's alway return `0` 

This is my code to use with `Duration` to calculate

```
    fun getDurationBetween2Date(originalDate: PlainDate, targetDate: PlainDate): Long {
        val timeMetric = Duration.`in`(CalendarUnit.MONTHS).between(originalDate, targetDate)
        return if (timeMetric.isPositive) timeMetric.getPartialAmount(CalendarUnit.MONTHS)
        else -timeMetric.getPartialAmount(CalendarUnit.MONTHS)
    }
```

returned is a Long type.

Could you teach me some advice.

I use `Kotlin` and Time4A lib
Thanks

**Comment by MenoData** [comment]
First to say, you can strongly simplyfy your expression with the same effect and result:

`long result = CalendarUnit.MONTHS.between(originalDate, targetDate);`

Furthermore, if your input consists of two calendar dates including the day of month then the day of month is taken into account in your calculation. That is the same behaviour as in standard Java. More precisely, if the day of month in the target date is smaller than the day of month in the starting date (earlier date) then the calculated difference will be decreased by one month (explaining your zero result).

So if you don't want to take into account the day of month then following trick can help:

        PlainDate originalDate = PlainDate.of(2019,8,31);
        PlainDate targetDate = PlainDate.of(2019,9,5);
        long result = 
            CalendarUnit.MONTHS.between(
                originalDate.with(PlainDate.DAY_OF_MONTH, 1), 
                targetDate.with(PlainDate.DAY_OF_MONTH, 1));
        System.out.println(result); // 1

When using Time4J you can also use the type `CalendarMonth` (representing just year+month) in the range-package:

        PlainDate originalDate = PlainDate.of(2019,8,31);
        PlainDate targetDate = PlainDate.of(2019,9,5);
        int result = Months.between(
            CalendarMonth.from(originalDate),
            CalendarMonth.from(targetDate)
        ).getAmount();
        System.out.println(result); // 1
