### ISSUE TITLE
Locale Support for Calendars

### ISSUE THREAD

**Issue by SaeedZhiany** [MenoData/Time4J#879]
Is this library locale supported for Calendars?

For example, sometimes I need to show Jalali (Shami) month names using English characters.
(e.g. showing "Mehr" instead of "مهر")

Thanks

**Comment by MenoData** [comment]
You can display Persian month names using following expression:

String mehr = PersianMonth.MEHR.getDisplayName(Locale.ENGLISH);

See also the [API](http://time4j.net/javadoc-en/net/time4j/calendar/PersianMonth.html#getDisplayName-java.util.Locale-).

**Comment by SaeedZhiany** [comment]
I understood. Thank you for your great contribution.
