### ISSUE TITLE
Test "MoonTest.moonPositionNY" fails in master and tag v5.5.

### ISSUE THREAD

**Issue by ams-tschoening** [MenoData/Time4J#886]
When trying to build master and tag `v5.5` simply by using `mvn test`, I get the following error:

    [ERROR] Failures:
    [ERROR]   MoonTest.moonPositionNY:234
    Expected: is <1.9708028936549722>
         but: was <1.970802893654973>
    [ERROR] Tests run: 24473, Failures: 1, Errors: 0, Skipped: 0

I'm using Windows 10 1909 and OpenJDK 8:

> openjdk version "1.8.0_232"
> OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
> OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)

After simply changing the expected value, all tests succeed. How should that be addressed?

**Comment by MenoData** [comment]
Vielen Dank für die Rückmeldung! (Thanks for feedback)

Well, here the double comparisons are far too strict and don't take into account that double calculations might have tiny rounding errors when executed on different platforms. Therefore I have switched the direct double comparisons to softer variants using a tolerance delta of one permille. You can also look at the comments mentioning reference values in USNO where the practical deltas are often bigger.
