### ISSUE TITLE
Incorrect sign in last term of calculation of mean lunar anomaly?

### ISSUE THREAD

**Issue by mistaven** [MenoData/Time4J#891]
Hello,

Please correct me if I am wrong, but I understood from Meeus 2nd Ed. (1998) that the last term of this line (474 in file `MoonPhase.java`) should not be positive, but instead _negative_:

Currently it is this:

```
double meanAnomalyMoon =
134.9633964 + (477198.8675055 + (0.0087414 + ((1.0 / 69699) + (1.0 / 14712000) * jct) * jct) * jct) * jct;
```

I believe it should be corrected to this:
```
double meanAnomalyMoon =
134.9633964 + (477198.8675055 + (0.0087414 + ((1.0 / 69699) - (1.0 / 14712000) * jct) * jct) * jct) * jct;
```

**Comment by MenoData** [comment]
Thank you very much for having found this typo in calculation. I will correct it as soon as possible..

**Comment by MenoData** [comment]
Small note: The calculation error is very small, however, so nobody needs to worry about it.
