### ISSUE TITLE
Ignoring option: -useuniqueclassmembernames

### ISSUE THREAD

**Issue by iamcalendar** [MenoData/Time4J#907]
In the case of enabling minify, we encounter the following warning when building our Android library (AAR):

> AGPBI: {"kind":"warning","text":"Ignoring option: -useuniqueclassmembernames","sources":[{"file":"C:\\Users\\Amir\\.gradle\\caches\\transforms-2\\files-2.1\\ad48a65f216623fc684f793154f00d44\\jetified-time4j-android-4.6-2020a\\proguard.txt","position":{"startLine":0,"startColumn":0,"startOffset":0,"endColumn":26,"endOffset":26}}],"tool":"R8"}

This is related to the first line of [consumer-proguard-rules.pro](https://github.com/MenoData/Time4A/blob/master/time4j-android/consumer-proguard-rules.pro) file: `-useuniqueclassmembernames`

Would this cause any problem? Is there any workaround?

**Comment by MenoData** [comment]
I don't think this will cause any problem if ignored. It is a valid option of Proguard in obfuscating context, see also the relevant section for `useuniqueclassmembernames` in the [documentation](https://www.guardsquare.com/en/products/proguard/manual/usage#obfuscationoptions).

But I agree, in case you really observe any serious problem then I can of course remove the line in the proguard file. It is not very important. By the way, I have recently updated my Android Studio to v4.0.0 and will check any relevant warnings left soon.

**Comment by iamcalendar** [comment]
Thank you for your attention.
