### ISSUE TITLE
convert utc time to local time

### ISSUE THREAD

**Issue by SaeedNoshadi89** [MenoData/Time4J#914]
hi.how can i convert utc time to local time in time4j?

**Comment by MenoData** [comment]
Use the methods [moment.toZonalTimestamp(tzid)](http://time4j.net/javadoc-en/net/time4j/Moment.html#toZonalTimestamp-net.time4j.tz.TZID-) or `moment.toLocalTimestamp()`. Explanation:

Objects of type `Moment` are UTC per definition, in terms of time zone as well as in terms of time scales. The methods convert to objects of type `PlainTimestamp` which is the local timestamp valid in the specified time zone resp. at specified zone offset.
