### ISSUE TITLE
Relative days in Dutch

### ISSUE THREAD

**Issue by Barachia** [MenoData/Time4J#922]
I found that the relative days for the PrettyPrint has some incorrect phrasings in Dutch. a bug, where upcoming days are printed as '[DAY] week', instead of the upcoming day.

Example:
```
import net.time4j.PrettyTime;
import java.time.ZonedDateTime;
import java.util.Locale;

...
ZonedDateTime time = ZonedDateTime.now().plusDays(2).withHour(23);
System.out.println(PrettyTime.of(Locale.forLanguageTag("nl")).printRelative(ZonedDateTime.from(time)));
```
Expected: "komende woensdag" (next Wednesday)
Result: "volgende week woensdag" (Wednesday week, not the upcoming Wednesday, but the next)

The change in the `relpattern_nl.properties` file should do the trick:

```
mon-=afgelopen maandag
mon+=komende maandag
tue-=afgelopen dinsdag
tue+=komende dinsdag
wed-=afgelopen woensdag
wed+=komende woensdag
thu-=afgelopen donderdag
thu+=komende donderdag
fri-=afgelopen vrijdag
fri+=komende vrijdag
sat-=afgelopen zaterdag
sat+=komende zaterdag
sun-=afgelopen zondag
sun+=komende zondag
```

I would also be in support of having the 'Wednesday week' option, which is 'woensdag over een week' in Dutch. Maybe these could be added in the future?

**Comment by MenoData** [comment]
Thanks for reporting these insufficient translations. The wrong (imprecise) translations were automatically transferred from CLDR-repository via a tool. With more than 90 supported languages, I cannot check every variant of translations so such input like from you is really valuable.

**Comment by MenoData** [comment]
About the phrasing "woensdag over een week" (=Wednesday in next week which is from Monday to Sunday?), I cannot support it because a) the week definition is rather dependent on the country and not the language and b) I don't see how to support the feature for all the other languages (CLDR does not contain such phrases in general). Sorry.
