### ISSUE TITLE
MINOR_01_LICHUN_315 can not be query out from ChineseCalendar(2021) at year 2021

### ISSUE THREAD

**Issue by dabdirb** [MenoData/Time4J#928]
We meet a problem that we can not query correct solar term of year 2021
```
import net.time4j.PlainDate;
import net.time4j.calendar.ChineseCalendar;
import net.time4j.calendar.SolarTerm;

PlainDate date = ChineseCalendar.ofNewYear(2021).with(ChineseCalendar.SOLAR_TERM, SolarTerm.MINOR_01_LICHUN_315).transform(PlainDate.class);
System.out.println(date);
```
output is 2022-02-04, it is not as expected, the correct date should be 2021-02-03.

The root cause is solar term in fact follow by Gregorian calendar  not  Lunar calendar (Chinese/Japanese/Korea).

ChineseCalendar(2020) is from 2020-01-25 to 2021-02-11
within this period there are 2 MINOR_01_LICHUN_315, 2020-02-04 and 2021-02-03, but if you use above code to query this Solar term it only return the first one, 2020-02-04
ChineseCalendar(2021) is from  2021-02-12 to 2022-01-31,
there are no MINOR_01_LICHUN_315 Solar term within this period, above code return 2022-02-04
So you can not query out MINOR_01_LICHUN_315 as 2021-02-03 by any method!

Chinese calendar from web <https://www.baidu.com/s?wd=%E4%B8%87%E5%B9%B4%E5%8E%86>

**Comment by MenoData** [comment]
Thanks for feedback. First to say, Time4J is able to query the lichun date you want. Look here:

```
    @Test
    public void query_MINOR_01_LICHUN_315() {
        ChineseCalendar gregorianNewYear = PlainDate.of(2021, 1, 1).transform(ChineseCalendar.class);
        assertThat(
            SolarTerm.MINOR_01_LICHUN_315.onOrAfter(gregorianNewYear).transform(PlainDate.class),
            is(PlainDate.of(2021, 2, 3)));
    }
```

You are right to say that Chinese calendar years might contain the solar term in question even twice or not at all. The code above looks for the first occurrence of the specified solar term after the current (contextual) gregorian year. 

I assume that gregorian calendar years are always associated with exactly one occurrence of given solar term. This assumption is at least correct for the lichun solar term but about a solar term like MINOR_12_XIAOHAN_285, I am not so sure without having done a test over the whole validity range of Chinese calendar.

About the current behaviour of the method `with(ChineseCalendar.SOLAR_TERM, SolarTerm.MINOR_01_LICHUN_315)`, its behaviour might be confusing but is documented [here](http://time4j.net/javadoc-en/net/time4j/calendar/ChineseCalendar.html#SOLAR_TERM):

> When manipulating then this element behaves as if the next solar term on or after new year is set. 

However, I should have clarified here that the Chinese New Year is meant as starting point not the gregorian New Year.

I am not quite sure how to classify it. 

a) Either it is simply underdocumented, and we can handle and fix it as documentation bug.
b) Or we change the behaviour of the method and use the start of the contextual gregorian year for the search for given solar term. 

Feel free to express your opinion about how to handle this issue.

**Comment by dabdirb** [comment]
The solar term LICHUN means "spring begins" and DAHAN mains "very cold winter", a Chinese year always begin at spring and end at winter, if we calculate MINOR_12_XIAOHAN_285 of year 2021 as 2021-01-05, it is not reasonable.
If we define a "SolarTerm Year", it always begin from LICHUN and end at DAHAN , the "SolarTerm Year" is not align with Chinese year or Gregorian year, but at least 22/24 of them is within a Chinese year or Gregorian year.
I can work around this issue by using your method, by calling onOrAfter() of gregorian year.
```
void listSolarTerms(int year) {
        ChineseCalendar chineseNewYear = ChineseCalendar.ofNewYear(year);
        for (SolarTerm value : SolarTerm.values()) {
            PlainDate date = chineseNewYear.with(ChineseCalendar.SOLAR_TERM, value).transform(PlainDate.class);
            if (value == SolarTerm.MINOR_01_LICHUN_315 && date.getYear() != year) {
                ChineseCalendar gregorianNewYear = PlainDate.of(year, 1, 1).transform(ChineseCalendar.class);
                date = value.onOrAfter(gregorianNewYear).transform(PlainDate.class);
            }
            System.out.print(date);
            System.out.print(' ');
            System.out.println(value);
        }
}
```
The output of listSolarTerms(2021) is 
```
2021-02-03 MINOR_01_LICHUN_315
2021-02-18 MAJOR_01_YUSHUI_330
2021-03-05 MINOR_02_JINGZHE_345
2021-03-20 MAJOR_02_CHUNFEN_000
2021-04-04 MINOR_03_QINGMING_015
2021-04-20 MAJOR_03_GUYU_030
2021-05-05 MINOR_04_LIXIA_045
2021-05-21 MAJOR_04_XIAOMAN_060
2021-06-05 MINOR_05_MANGZHONG_075
2021-06-21 MAJOR_05_XIAZHI_090
2021-07-07 MINOR_06_XIAOSHU_105
2021-07-22 MAJOR_06_DASHU_120
2021-08-07 MINOR_07_LIQIU_135
2021-08-23 MAJOR_07_CHUSHU_150
2021-09-07 MINOR_08_BAILU_165
2021-09-23 MAJOR_08_QIUFEN_180
2021-10-08 MINOR_09_HANLU_195
2021-10-23 MAJOR_09_SHUANGJIANG_210
2021-11-07 MINOR_10_LIDONG_225
2021-11-22 MAJOR_10_XIAOXUE_240
2021-12-07 MINOR_11_DAXUE_255
2021-12-21 MAJOR_11_DONGZHI_270
2022-01-05 MINOR_12_XIAOHAN_285
2022-01-20 MAJOR_12_DAHAN_300
```

I suggest add new function such as SolarTerm.ofYear() to fast query out solar term date of a year, it is clear and better than add document or change current Chinese year class.

**Comment by MenoData** [comment]
Finally, I have improved the documentation of element `ChineseCalendar.SOLAR_TERM`. Furthermore, following new methods are now in the enum class `SolarTerm`:

`public static <D extends EastAsianCalendar<?, D>> List<D> list(
        int gregorianYear,
        Chronology<D> chronology
    )`
`public <D extends EastAsianCalendar<?, D>> ChronoOperator<D> sinceLichun()`
`public <D extends EastAsianCalendar<?, D>> ChronoOperator<D> sinceNewYear()`
