### ISSUE TITLE
fast question,using javafx time4jui.

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [MenoData/Time4J#930]
I tried>
net.time4j.ui.javafx.CalendarPicker obj=net.time4j.ui.javafx.CalendarPicker.gregorianWithSystemDefaults();
		javafx.scene.Scene scn=new javafx.scene.Scene(obj, 300, 250);
		Stage stage = new Stage();
        stage.setTitle("Date pick test");//scn.getChildren().add(obj);
        stage.setScene(scn);
        stage.show();

it does not seems to show any stuff.Any idea?

**Comment by MenoData** [comment]
Thank you for your interest in my library. Your code example has no reference to the JavaFX environment resp. application. As starting point, you can study the [JUnit-test](https://github.com/MenoData/Time4J/blob/master/ui/src/test/java/net/time4j/ui/javafx/CalendarPickerTest.java) of Time4J.

While your `Stage`-object is just self-created my JUnit test takes it from JavaFX-app as parameter of the `start()`-method of `Application`-object. Just try it yourself and change your code appropriately.

By the way, you might also get good answers on the stackoverflow website - especially in this case which does not appear to be directly related to Time4J.

**Comment by MenoData** [comment]
I have seen that you have posted your question now also on Stackoverflow-website. The [answer](https://stackoverflow.com/a/65858027/2491410) of @jetspiking will point you in the right direction.

Your mistake was simply to have put the application launch into the wrong method. The launch must be within the main() method, or for a JUnit-test - within the open()-method. The JavaFX-stuff itself is only executed within the start()-method.
