### ISSUE TITLE
Respect Unicode extension `hc`

### ISSUE THREAD

**Issue by s5bug** [MenoData/Time4J#933]
As of right now I'm unable to override the clock system in a locale with `hc` like `en-US-u-hc-h23` for 0-23 clock hours. If possible, I'd like to store this information in the language tab instead of as a separate variable. Is this possible?

**Comment by MenoData** [comment]
This feature is not yet offered by Time4J. I have found some documentation in [CLDR](https://unicode.org/reports/tr35/#UnicodeHourCycleIdentifier).

If I understand you right then you would like to set the hc-preference in the locale and override any default time patterns in the format engine. This practically indicates the need to process/change format patterns created by default. For example, if the locale is "en-US-u-hc-h23" then the time-style-pattern needs to be changed from "hh:mm a" to "HH:mm" and vice versa. All style based formatters are concerned here.

Actually, the class `ChronoFormatter` supports following unicode extensions:

ca, nu, fw, rg (see the [tutorial](http://time4j.net/tutorial/i18n.html#x1), too)

**Comment by MenoData** [comment]
Some kind of time style pattern processing is realized in the sister project Time4A where the default preference for 12/24-hour mode is evaluated. Maybe [this code](https://github.com/MenoData/Time4A/blob/dfb54f3865c54259ecea1078f547a785261f7538/time4j-android/src/main/java/net/time4j/android/spi/AndroidResourceLoader.java#L247) could be a start for the implementation in Time4J.
