### ISSUE TITLE
[Question] How to get sunrise/sunset time?

### ISSUE THREAD

**Issue by sblantipodi** [MenoData/Time4J#949]
Hi,
how can I get the sunrise/sunset time?

I know that it can be possible by knowing the GPS coordinates, but how can I get the GPS coordinates? :)

**Comment by MenoData** [comment]
You can calculate sunrise and sunset based on the class [SolarTime](http://time4j.net/javadoc-en/net/time4j/calendar/astro/SolarTime.html). Its documentation contains examples how to do this task using geographic latitudes and longitudes.

But I can only speculate why you ask for getting these coordinates?! Maybe you are on an Android device. If so then you might start with [this older issue](https://github.com/MenoData/Time4J/issues/683) and the link there.

**Comment by sblantipodi** [comment]
Thanks for the answer, I'm on WIndows/Linux and I don't see a "free" method to get the coordinates. :)
Without coordinates it seems that I can't get the Sunrise/Sunset that is what I am searching for.

**Comment by MenoData** [comment]
If on a Windows/Linux-platform then it is clear that a computer cannot give you in general these coordinates. You will need any kind of GPS-enabled service or device. Or you simply ask the user for those coordinates via an input mask in the user interface which is my recommendation when ever your computer does not know where it is suited resp. located.
