### ISSUE TITLE
Test fails during build

### ISSUE THREAD

**Issue by hylkevds** [MenoData/Time4J#961]
Using `mvn install` gives an error during unit testing.

Full build log:
https://github.com/hylkevds/Time4J/runs/4564324156?check_suite_focus=true#step:4:6711
```
Error:  Failures: 
Error:    IntervalCollectionTest.collectionOfInstantIntervals:1267 
Expected: is <[[2021-12-17T19:03:21.211193Z/2021-12-17T19:03:22.211193Z)]>
     but: was <[[2021-12-17T19:03:21.211199Z/2021-12-17T19:03:22.211193Z)]>

```

**Comment by MenoData** [comment]
Thank you for your contribution. Although I cannot reproduce it on my machine (which has probably less than microsecond precision), I can indeed see what was wrong. The expression `Instant.now()` must not be called more than once during test method in order to avoid such microsecond deltas.

**Comment by MenoData** [comment]
I have now fixed it. Please give me feedback if your build now succeeds.

**Comment by hylkevds** [comment]
Yep, works fine now.
Thanks for the quick fix!
