### ISSUE TITLE
add module-info.class for Java9+ modular system

### ISSUE THREAD

**Issue by GG-A** [MenoData/Time4J#962]
Could you add `module-info.class` to `Time4j` for `Java9+` modular system?

**Comment by MenoData** [comment]
Thanks for your feedback. I have already thought about it and done some experiments with build configuration. But I have not found any good way to achieve compatibility with both Java 8 and modular Java 9.

So I get the impression to abandon compatibility with Java 8 and just switch over to Java 9. However, I am not sure how other users would think about this option.

**Comment by GG-A** [comment]
Maybe you can try adding this build configuration to your `pom.xml`: [maven-compiler-plugin: Older projects with module-info](https://maven.apache.org/plugins/maven-compiler-plugin/examples/module-info.html)

**Comment by MenoData** [comment]
I have struggled a long time with this issue but finally I have to say: Sorry, will not implement it at least not in this or next year. Maybe later when Java 8 is much more out of common usage. Main reasons: 

- A date- and time-library does not urgently need modules.
- I have not found any good way to release a build which will work on Java-8 AND with modules on Java-9 AND will work in my development area.
- At least automatic module names are already supported.

See also the small debate on issue #964
