### ISSUE TITLE
Please Solve this bug

### ISSUE THREAD

**Issue by Manjur13** [MenoData/Time4J#969]
java.lang.ExceptionInInitializerError
        at net.time4j.base.ResourceLoader.getInstance(ResourceLoader.java:139)

**Comment by MenoData** [comment]
Please add some context to your problem, for example: 

- Which platform do you use (Time4J or Time4A on Android)? 
- How do you initialize your app (Android needs a special initialization)?

**Comment by JackyXman** [comment]
I have some crash 
i used in  React native,but crash 
`
 implementation group: 'net.time4j', name: 'time4j-android', version: '4.8-2021a'

public class DatePickerModule extends LegoRNJavaModule {

    public DatePickerModule(ReactApplicationContext context) {
        super(context);
        ApplicationStarter.initialize(context, false); // false = no need to prefetch on time data background tread
    }
`

# create_react_context 2596
java.lang.NoClassDefFoundError
<clinit> failed for class net.time4j.g0.d; see exception in other thread

![image](https://user-images.githubusercontent.com/10811997/187134391-e908e47c-3172-4335-931e-9f97fb1bf9a2.png)

**Comment by MenoData** [comment]
This must be a proguard issue with your configuration. Maybe you might solve it with adding following line to your proguard file:

`-keep class net.time4j.base.ResourceLoader`

Of course, if you don't apply Proguard at all, then your problem will surely go away (what you can do at least for testing if this is really a proguard issue).

**Comment by JackyXman** [comment]
now I add 
`
-keep public class net.time4j.base.ResourceLoader
`
,
before i added two keep
`
-keep public class net.time4j.android.ApplicationStarter
-keep public class net.time4j.PrettyTime
`

and  now  i modify  **ApplicationStarter.initialize**  in the Applicaion oncreate()  ApplicationStarter.initialize(application, false);
**the second params is false  ok?**

**Comment by JackyXman** [comment]
> This must be a proguard issue with your configuration. Maybe you might solve it with adding following line to your proguard file:
> 
> `-keep class net.time4j.base.ResourceLoader`
> 
> Of course, if you don't apply Proguard at all, then your problem will surely go away (what you can do at least for testing if this is really a proguard issue).

now I add
-keep public class net.time4j.base.ResourceLoader
,
before i added two keep
-keep public class net.time4j.android.ApplicationStarter -keep public class net.time4j.PrettyTime

and now i modify ApplicationStarter.initialize in the Applicaion oncreate() ApplicationStarter.initialize(application, false);
the second params is false ok?

**Comment by MenoData** [comment]
Have you now tested your new proguard setup? Anyway, if your proguard configuration does not ignore the project file [consumer-proguard-rules](https://github.com/MenoData/Time4A/blob/master/time4j-android/consumer-proguard-rules.pro) then you should really not observe any problems. My impression is: Your project setup seems to ignore or override this important file.

I cannot reproduce your error.
